# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: CI

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

env:
  SDK_BUILDER_IMAGE: 'ghcr.io/xmos/sdk_app_builder:develop'

jobs:
  build_host_apps:
    name: Build host applications
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull SDK builder
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Build
        run: |
          docker run --rm -w /xcore_sdk -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_host_apps.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: host_apps
          path: ./dist_host

  build_main_examples:
    name: Build main example applications
    runs-on: ubuntu-latest
    needs: build_host_apps
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull SDK builder image
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Download host build artifacts
        uses: actions/download-artifact@v3
        with:
          name: host_apps
          path: ./dist_host
          
      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /sln_voice -v ${{github.workspace}}:/sln_voice ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_main_examples.sh

      - name: Save metadata
        run: |
          bash tools/ci/log_metadata.sh ./dist/main_examples_metadata.json

      - name: Save example app firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sln_voice_main+example_apps
          path: |
            ./dist/*.xe
            ./dist/*.fs
            ./dist/*.json

  build_misc_examples:
    name: Build misc example applications
    runs-on: ubuntu-latest
    needs: build_host_apps
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull SDK builder image
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Download host build artifacts
        uses: actions/download-artifact@v3
        with:
          name: host_apps
          path: ./dist_host
          
      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /sln_voice -v ${{github.workspace}}:/sln_voice ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_misc_examples.sh

      - name: Save metadata
        run: |
          bash tools/ci/log_metadata.sh ./dist/misc_examples_metadata.json

      - name: Save example app firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sln_voice_misc_example_apps
          path: |
            ./dist/*.xe
            ./dist/*.fs
            ./dist/*.json

  build_tests:
    name: Build tests and test applications
    runs-on: ubuntu-latest
    needs: build_host_apps
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Pull SDK builder image
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Download host build artifacts
        uses: actions/download-artifact@v3
        with:
          name: host_apps
          path: ./dist_host

      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /sln_voice -v ${{github.workspace}}:/sln_voice ${SDK_BUILDER_IMAGE} bash -l tools/ci/build_tests.sh

      - name: Save metadata
        run: |
          bash tools/ci/log_metadata.sh ./dist/tests_metadata.json

      - name: Save example application firmware artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sln_voice_test_apps
          path: |
            ./dist/*.xe
            ./dist/*.fs
            ./dist/*.json
