# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: Documentation

on:
  push:
    branches:
      - 'develop'
      - 'main'
  pull_request:
    branches:
      - 'develop'
      - 'main'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

env:
  DOC_BUILDER_IMAGE: 'ghcr.io/xmos/doc_builder:latest'

jobs:
  build_documentation:
    name: Build and package documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Pull documentation builder docker image
        run: |
          docker pull ${DOC_BUILDER_IMAGE}
      
      - name: Build documentation
        run: |
          docker run --rm -t -u "$(id -u):$(id -g)" -v ${{ github.workspace }}:/build -e PDF=1 -e REPO:/build -e EXCLUDE_PATTERNS=/build/doc/exclude_patterns.inc -e DOXYGEN_INCLUDE=/build/doc/Doxyfile.inc -e DOXYGEN_INPUT=ignore ${DOC_BUILDER_IMAGE}

      - name: Save HTML artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sln_voice_html_docs
          path: doc/_build/html
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 

      - name: Save PDF artifacts
        uses: actions/upload-artifact@v3
        with:
          name: sln_voice_pdf_docs
          path: doc/_build/pdf
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn` 
